//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSystemDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime TaskDate { get; set; }
        public int Important { get; set; }
        public int Status { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
